### ISSUE TITLE
Add Blog

### ISSUE THREAD

**Issue by OhmGeek** [OhmGeek/aidans-jcr#8]
We want a blog on the site so we can link recent blog articles on the main page.
This is used by someone to publish news (about events).

Need to have a page, with info about the poster, time, date, and also the content. Use STREAM-FIELD.
Have FB and Twitter Integration for pages, so that they can control through the site (website is the middle of life)

**Comment by OhmGeek** [comment]
Basic blog articles added in #9

**Comment by OhmGeek** [comment]
Still need Streamfield implementation. Also need to improve UI itself.

**Comment by OhmGeek** [comment]
Working on this now. User's full name is done now.

**Comment by OhmGeek** [comment]
# TODO:
- [ ] Front page news block (with the ability to hide it) is needed
- [ ] Share on Facebook/Twitter links are needed on the blog pages
- [ ] Basic streamfield implementation to come later. This isn't as important at the moment.
